HEPMCLOCATION=/afs/cern.ch/user/e/erichter/work/public/HiggsCP/external/HEPMC/HepMC/
PHOTOSLOCATION=/afs/cern.ch/user/e/erichter/work/public/HiggsCP/external/PHOTOS/PHOTOS/
PYTHIALOCATION=/afs/cern.ch/user/e/erichter/work/public/HiggsCP/external/PYTHIA/pythia8201/
TAUSPINNERLOCATION=/afs/cern.ch/user/e/erichter/work/public/HiggsCP/external/TAUOLA/TAUOLA/TauSpinner/
TAUOLALOCATION=/afs/cern.ch/user/e/erichter/work/public/HiggsCP/external/TAUOLA/TAUOLA/
LHAPDFLOCATION=/afs/cern.ch/user/e/erichter/work/public/HiggsCP/external/LHAPDF/lhapdf/
