HEPMCLOCATION=/people/plgerichter/storage/testarea/Ela2021/TauSpinnerFrame/external/HEPMC/HepMC/
PHOTOSLOCATION=/people/plgerichter/storage/testarea/Ela2021/TauSpinnerFrame/external/PHOTOS/PHOTOS/
PYTHIALOCATION=/people/plgerichter/storage/testarea/Ela2021/TauSpinnerFrame/external/PYTHIA/pythia8201/
TAUSPINNERLOCATION=/people/plgerichter/storage/testarea/Ela2021/TauSpinnerFrame/external/TAUOLA/TAUOLA/TauSpinner/
TAUOLALOCATION=/people/plgerichter/storage/testarea/Ela2021/TauSpinnerFrame/external/TAUOLA/TAUOLA/
LHAPDFLOCATION=/people/plgerichter/storage/testarea/Ela2021/TauSpinnerFrame/external/LHAPDF/lhapdf/
